### ISSUE TITLE
Re-usability/"choose a configuration" system

### ISSUE THREAD

**Issue by aurtzy** [aurtzy/linux-autosetup#42]
Introduce some re-usability system in order to share similar configs instead of creating multiple slightly varying configs or mixing packs that will never be used on some systems; e.g. laptops may need power settings apps where desktops will never need them, but otherwise will have identical setups

- Idea iteration 1:
```
default: sudo pacman -S "$@"
---
default:
    apt: sudo apt install "$@"
    pacman: sudo pacman -S "$@"
```
The first configuration automatically selects "default" as the default cmd_preset. The second would prompt for whichever command to use. Allowing for cmd_preset defaults or passing option arg seems less trivial this way, though.

- Idea iteration 2:
```
config_type: single (or omit)
..
packs:
    pack1:
        modules: ...
---
config_type: multi
systems:
    - ubuntu
    - arch
..
packs:
    pack1:
        default/all:
            modules: ...
        ubuntu:
            modules: ...
```
A new config setting "config_type", where omitting or setting it to "single" indicates an essentially normal config like it is already now - Packs are all defined on a global level, and there is no distinguishing between systems that packs are for.

Setting it to "multi" would add an extra level to the user config, making it slightly more complex if desired (not forced), but allowing an inheritance-like system where there is a default global level which can be overridden for more specific systems. If the default level is omitted, possibly only initialize the pack when the user performs an autosetup specifically for that system type.

Still unsure how to elegantly implement layered inheritance (e.g. default/all -> debian -> ubuntu) and specifying systems in the config.
